-- Subqueries
USE EMPRESA_DB

-- TRAGA A DESCRIÇÃO DOS PRODUTOS QUE POSSUEM O PREÇO MAIOR QUE A MÉDIA DE TODOS OS PRODUTOS
SELECT P.Descricao FROM TB_PRODUTO p
WHERE P.Preco > ( SELECT AVG(P2.Preco) FROM TB_PRODUTO P2 )

-- TRAGA TODOS OS CLIENTES QUE EXISTAM PEDIDOS NO MÊS 7 DE 1996
SELECT C. *  FROM TB_CLIENTES C
WHERE EXISTS ( SELECT * FROM TB_PEDIDO P 
               WHERE C.ClienteId = P.ClienteId AND P.DataPedido BETWEEN '1996-07-01' AND '1996-07-31')

-- TRAGA O NOME E O TOTAL DE PEDIDOS DE CADA CLEIENTE
SELECT C.NomeCompleto, (SELECT COUNT(*) FROM TB_PEDIDO P WHERE P.ClienteId = C.ClienteId) [Total Pedidos]
FROM TB_CLIENTES C
ORDER BY [Total Pedidos]

-- DELETE COM Subquerys
DELETE FROM TB_PEDIDO
WHERE FuncionarioId = ( SELECT FuncionarioId FROM TB_FUNCIONARIO
							WHERE Cargo = 'Vice-Presidente de Vendas')

SELECT * FROM TB_PEDIDO
WHERE FuncionarioId = ( SELECT FuncionarioId FROM TB_FUNCIONARIO
							WHERE Cargo = 'Vice-Presidente de Vendas')